// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNTCQywyiwb2m9ZFr0arWT0qO4_TjxDzk',
    appId: '1:1077579732943:web:327a0dfc187e3bcbc124ba',
    messagingSenderId: '1077579732943',
    projectId: 'yatra-ad',
    authDomain: 'yatra-ad.firebaseapp.com',
    storageBucket: 'yatra-ad.appspot.com',
    measurementId: 'G-BN5BELHEH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi2GNwZ3ROfiyx20Kz-oscOvN2RMu677c',
    appId: '1:1077579732943:android:15edcc5ad6ea5864c124ba',
    messagingSenderId: '1077579732943',
    projectId: 'yatra-ad',
    storageBucket: 'yatra-ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQdnHljpk0O_riX8ZQJnZWcJ-2mQjUTkI',
    appId: '1:1077579732943:ios:33c5d06809c90119c124ba',
    messagingSenderId: '1077579732943',
    projectId: 'yatra-ad',
    storageBucket: 'yatra-ad.appspot.com',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQdnHljpk0O_riX8ZQJnZWcJ-2mQjUTkI',
    appId: '1:1077579732943:ios:5d566763122aa780c124ba',
    messagingSenderId: '1077579732943',
    projectId: 'yatra-ad',
    storageBucket: 'yatra-ad.appspot.com',
    iosBundleId: 'com.example.dash.RunnerTests',
  );
}
