// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeDRogt1abXVf_aWmKLwTZhW_HexEH1h8',
    appId: '1:489357695265:web:3a9b5dac6f67e00a69c660',
    messagingSenderId: '489357695265',
    projectId: 'yat-ra',
    authDomain: 'yat-ra.firebaseapp.com',
    storageBucket: 'yat-ra.appspot.com',
    measurementId: 'G-JTNHY8R7K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe2hAFh9Y_gjaMgjHZnzuW-yh4BZXLsaA',
    appId: '1:489357695265:android:bd740e1d22003bd169c660',
    messagingSenderId: '489357695265',
    projectId: 'yat-ra',
    storageBucket: 'yat-ra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmLlXu6yk_AOgPTEkhmH11ttJKthouSi4',
    appId: '1:489357695265:ios:a29aaaee634d66d569c660',
    messagingSenderId: '489357695265',
    projectId: 'yat-ra',
    storageBucket: 'yat-ra.appspot.com',
    androidClientId: '489357695265-31pqrr607abkmfncte6a3ineoh2l6ire.apps.googleusercontent.com',
    iosClientId: '489357695265-0p12j0qj6mfq5a0dh5pos1t9ed9grs2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmLlXu6yk_AOgPTEkhmH11ttJKthouSi4',
    appId: '1:489357695265:ios:28de65a07d3bd4e769c660',
    messagingSenderId: '489357695265',
    projectId: 'yat-ra',
    storageBucket: 'yat-ra.appspot.com',
    androidClientId: '489357695265-31pqrr607abkmfncte6a3ineoh2l6ire.apps.googleusercontent.com',
    iosClientId: '489357695265-tq6ek1bkajj45apoi1kldgotgml8jd6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash.RunnerTests',
  );
}
